import type {NextPage} from "next";
import Head from "next/head";
import {signIn, signOut, useSession} from "next-auth/react";
import {trpc} from "../utils/trpc";
import {useState} from "react";

const Messages = () => {
  const {data: messages, isLoading} = trpc.useQuery(["guestbook.getAll"]);

  if (isLoading) return <div>Fetching messages...</div>;

  return (
    <div className="flex flex-col gap-4">
      {messages?.map((msg, index) => {
        return (
          <>
            <div key={index} className={"bg-gray-500 font-bold flex justify-between text-gray-200 p-2 rounded-2xl"}>
              <p className={"pl-1.5"}>{msg.message}</p>
              <span className={"pr-1.5"}>- {msg.name}</span>
            </div>
            {/*<br/>*/}
          </>
        )
          ;
      })}
    </div>
  );
};

const Home: NextPage = () => {
  //States and Session
  const {data: session, status} = useSession();
  const [message, setMessage] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(false);

  //tRPC stuff
  const ctx = trpc.useContext();
  const postMessage = trpc.useMutation("guestbook.postMessage", {
    onMutate: () => {
      ctx.cancelQuery(["guestbook.getAll"]);

      let optimisticUpdate = ctx.getQueryData(["guestbook.getAll"]);
      if (optimisticUpdate) {
        ctx.setQueryData(["guestbook.getAll"], optimisticUpdate);
      }
    },
    onSettled: () => {
      ctx.invalidateQueries(["guestbook.getAll"]);
    },
  });

  const handleSubmit = () => {
    setLoading(true);
    postMessage.mutate({
      name: session?.user?.name as string,
      message: message,
    });
    setMessage("");
    setLoading(false);
  }

  //Check session
  if (status === "loading") {
    return <h1 className={"flex flex-col items-center pt-4"}>Loading...</h1>
  }

  return (
    <>
      <Head>
        <title>Guestbook</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={"flex flex-col items-center"}>
        <h1 className={"text-3xl pt-4 font-bold"}>Guestbook</h1>

        <div className={"pt-10"}>
          {session ? (
            <div>
              <div className={"flex justify-between items-center"}>
                <p className={"text-2xl font-bold select-none"}>{session.user?.name}</p>
                <button onClick={() => signOut()}
                        className={"bg-purple-600 p-2 rounded-3xl font-bold hover:bg-purple-400 transition ease-in pl-8 pr-8 "}>Logout
                </button>
              </div>

              <div className={"pt-6 justify-between flex"}>
                <input
                  type={"text"}
                  name={"message"}
                  id={"message"}
                  value={message}
                  placeholder={"Your message..."}
                  maxLength={100}
                  onChange={(event) => setMessage(event.target.value)}
                  className={"px-4 pr-36 py-2 rounded-md border-2 border-zinc-800 bg-neutral-900 focus:outline-none"}
                />
                <button
                  type={"submit"}
                  disabled={loading || message.length < 1 || message.length > 100}
                  className={"p-2 rounded-3xl border-2 bg-purple-600 font-bold border-zinc-800 focus:outline-none hover:bg-purple-400 transition ease-in pl-8 pr-8 disabled:bg-purple-50 "}
                  onClick={() => handleSubmit()}
                >Submit
                </button>
              </div>

              <div className={"pt-10 min-w-[500px]"}>
                <Messages/>
              </div>
            </div>
          ) : (
            <div>
              <div className={"flex justify-between items-center"}>
                <button onClick={() => signIn("discord")}
                        className={"mx-auto ml-2 bg-purple-600 p-4 rounded-full font-bold focus:outline-none border-zinc-800 border-2 hover:bg-purple-400 transition ease-in"}>Log
                  In
                  with Discord
                </button>
                <p className={"font-bold text-2xl"}>Log in to send a message</p>
              </div>
              <div className={"pt-10"}/>
              <div className={"min-w-[500px]"}>
                <Messages/>
              </div>
            </div>
          )}
        </div>

      </main>
    </>
  );
};

export default Home;
